AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for creating a short URL from another URL (part of the Short URL generator)

Globals:
  Function:
    Timeout: 20

Parameters:
  DynamoURL: #Connection URL to the DynamoDB instance
    Type: String
    Default: "http://dynamo-local:8000"
  BaseURL: #Base URL of short URLs that are generated, e.g. http://me.li
    Type: String
    Default: "http://localhost:3000"
  RedisURL: #Connection URL to the Redis cache cluster instance
    Type: String
    Default: "redis://redis-server:6379/"  
  WriterFactory:  #Factory class used to persist URLs at the data layer
    Type: String
    Default: "shorturls.dynamodao.config.DynamoDAOFactory"    
  IdGeneratorFactory: #Factory class used to generate codes of the short URLs
    Type: String
    Default: "createshorturl.generator.SecureRandomGenerator"    
  RandomLength: #Length of the codes generated in short URLs. Suggested at least 5 characters.
    Type: Number
    Default: "7"
    MinValue: "5"  
  RandomAlgorithm: #Algorithm used to generate random codes for short URLs
    Type: String
    Default: "SHA1PRNG"
  RandomSeed: #Seed used to generate random codes for short URLs
    Type: String
    Default: "79CVJGJ"    
  RandomAlphabet: #Alphabet used for generating short URLs
    Type: String
    Default: "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
  CacheEnabled: #If enabled, cache is used
    Type: String
    Default: "false"
  CacheFactory: #Factory class used to configure cache
    Type: String
    Default: "shorturls.cache.config.RedisCacheFactory"
  DynamoRandomRange: #Random range used as suffix of partition keys for avoiding hot partitions on DynamoDB
    Type: Number
    Default: 1
    MinValue: 1
  ContentType: #String to know the content-type of the requests when creating short urls
    Type: String
    Default: "content-type"
Resources:
  CreateShortURLFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ../createshorturl
      Handler: createshorturl.apigateway.CreateShortURLGW::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      Policies:
      - AmazonDynamoDBFullAccess
      - AmazonVPCCrossAccountNetworkInterfaceOperations
      MemorySize: 512
      Environment: 
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 
          DYNAMO_URL: !Ref DynamoURL
          BASE_URL: !Ref BaseURL
          WRITER_FACTORY: !Ref WriterFactory
          ID_GENERATOR_FACTORY: !Ref IdGeneratorFactory
          RANDOM_LENGTH: !Ref RandomLength
          RANDOM_ALPHABET: !Ref RandomAlphabet
          RANDOM_ALGORITHM: !Ref RandomAlgorithm
          RANDOM_SEED: !Ref RandomSeed
          REDIS_URL: !Ref RedisURL
          CACHE_ENABLED: !Ref CacheEnabled
          CACHE_FACTORY: !Ref CacheFactory 
          DYNAMO_RANDOM_RANGE: !Ref DynamoRandomRange
          CONTENT_TYPE: !Ref ContentType
      Events:
        CreateShortURLEvent:
          Type: Api 
          Properties:
            Path: /urls
            Method: post
  CreateShortURLSecondsFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ../createshorturl
      Handler: createshorturl.apigateway.CreateShortURLSecondsGW::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      Policies:
      - AmazonDynamoDBFullAccess
      - AmazonVPCCrossAccountNetworkInterfaceOperations
      MemorySize: 512
      Environment: 
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 
          DYNAMO_URL: !Ref DynamoURL
          BASE_URL: !Ref BaseURL
          WRITER_FACTORY: !Ref WriterFactory
          ID_GENERATOR_FACTORY: !Ref IdGeneratorFactory
          RANDOM_LENGTH: !Ref RandomLength
          RANDOM_ALPHABET: !Ref RandomAlphabet
          RANDOM_ALGORITHM: !Ref RandomAlgorithm
          RANDOM_SEED: !Ref RandomSeed
          REDIS_URL: !Ref RedisURL
          CACHE_ENABLED: !Ref CacheEnabled
          CACHE_FACTORY: !Ref CacheFactory
          DYNAMO_RANDOM_RANGE: !Ref DynamoRandomRange
      Events:
        CreateShortURLHoursEvent:
          Type: Api 
          Properties:
            Path: /expiringurls
            Method: post