AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Short URL Generator
  SAM Template for Short URL generator

Globals:
  Function:
    Timeout: 20

Parameters:
  DynamoURL:
    Type: String
    Default: "http://dynamo-local:8000"
  BaseURL:
    Type: String
    Default: "http://127.0.0.1:3000"
  RedisURL:
    Type: String
    Default: "redis://redis-server:6379/"  
  CacheEnabled:
    Type: String
    Default: "false"
  QueryFactory:
    Type: String
    Default: "shorturls.dynamodao.DynamoDAOFactory" 
  CacheFactory:
    Type: String
    Default: "shorturls.cache.RedisCacheFactory"   
  EventsFactory:
    Type: String
    Default: "com.meli.kafka.KafkaFactory"
  CacheFactory:
    Type: String
    Default: "shorturls.cache.RedisCacheFactory"   
  EventsFactory:
    Type: String
    Default: "com.meli.kafka.KafkaFactory"
  KafkaBrokers: 
    Type: String
    Default: "kafka:29092"
  KafkaClientId: 
    Type: String
    Default: "client1"
  KafkaTopicName: 
    Type: String
    Default: "geturl"
  KafkaEnabled: 
    Type: String
    Default: "false"
  RandomAlphabet:
    Type: String
    Default: "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
Resources:
  GetURLFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ../geturl
      Handler: geturl.apigateway.GetURLGW::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      Policies:
      - AmazonDynamoDBFullAccess
      MemorySize: 512
      Environment: 
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
          DYNAMO_URL: !Ref DynamoURL
          BASE_URL: !Ref BaseURL
          REDIS_URL: !Ref RedisURL
          CACHE_ENABLED: !Ref CacheEnabled
          QUERY_FACTORY: !Ref QueryFactory
          CACHE_FACTORY: !Ref CacheFactory
          EVENTS_FACTORY: !Ref EventsFactory
          KAFKA_BROKERS: !Ref KafkaBrokers
          KAFKA_CLIENTID: !Ref KafkaClientId
          KAFKA_TOPICNAME: !Ref KafkaTopicName
          KAFKA_ENABLED: !Ref KafkaEnabled
          RANDOM_ALPHABET: !Ref RandomAlphabet

      Events:
        GetURLEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /urls/{code}
            Method: get
  GetLongURLFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ../geturl
      Handler: geturl.apigateway.GetLongURLGW::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      Policies:
        - AmazonDynamoDBFullAccess
      MemorySize: 512
      Environment: 
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
          DYNAMO_URL: !Ref DynamoURL
          BASE_URL: !Ref BaseURL
          REDIS_URL: !Ref RedisURL
          CACHE_ENABLED: !Ref CacheEnabled
          QUERY_FACTORY: !Ref QueryFactory
          CACHE_FACTORY: !Ref CacheFactory
          EVENTS_FACTORY: !Ref EventsFactory
          KAFKA_BROKERS: !Ref KafkaBrokers
          KAFKA_CLIENTID: !Ref KafkaClientId
          KAFKA_TOPICNAME: !Ref KafkaTopicName
          KAFKA_ENABLED: !Ref KafkaEnabled
      Events:
        GetLongURLEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /longURLS
            Method: get