AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Short URL Generator
  SAM Template for Short URL generator

Globals:
  Function:
    Timeout: 20

Parameters:
  BaseURL:
    Type: String
    Default: "http://localhost:3000"
  DynamoURL:
    Type: String
    Default: "http://dynamo-local:8000"
  DeleterFactory:
    Type: String
    Default: "shorturls.dynamodao.DynamoDAOFactory"    
  CacheFactory:
    Type: String
    Default: "shorturls.cache.config.RedisCacheFactory"
  CacheEnabled:
    Type: String
    Default: "false"
  RedisUrl:
    Type: String
    Default: "redis://rediserver:6379/"
  RandomAlphabet:
    Type: String
    Default: "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
Resources:
  DeleteShortFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ../deleteshorturl
      Handler: deleteshorturl.apigateway.DeleteShortURLGW::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      Policies:
      - AmazonDynamoDBFullAccess
      - AmazonVPCCrossAccountNetworkInterfaceOperations
      MemorySize: 512
      Environment: 
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 
          BASE_URL: !Ref BaseURL
          DYNAMO_URL: !Ref DynamoURL
          DELETER_FACTORY: !Ref DeleterFactory
          CACHE_FACTORY: !Ref CacheFactory
          CACHE_ENABLED: !Ref CacheEnabled
          RANDOM_ALPHABET: !Ref RandomAlphabet
          REDIS_URL: !Ref RedisUrl
      Events:
        DeleteShortURLevent:
          Type: Api 
          Properties:
            Path: /shortURL
            Method: delete
  DeleteShortPathFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ../deleteshorturl
      Handler: deleteshorturl.apigateway.DeleteShortPathGW::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      Policies:
      - AmazonDynamoDBFullAccess
      - AmazonVPCCrossAccountNetworkInterfaceOperations
      MemorySize: 512
      Environment: 
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 
          BASE_URL: !Ref BaseURL
          DYNAMO_URL: !Ref DynamoURL
          DELETER_FACTORY: !Ref DeleterFactory
          CACHE_FACTORY: !Ref CacheFactory
          CACHE_ENABLED: !Ref CacheEnabled
          RANDOM_ALPHABET: !Ref RandomAlphabet
          REDIS_URL: !Ref RedisUrl
      Events:
        DeleteShortURLevent:
          Type: Api 
          Properties:
            Path: /urls/{code}
            Method: delete