AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for redirecting URLs from the short URL (part of the Short URL generator)

Globals:
  Function:
    Timeout: 20

Parameters:
  DynamoURL: #Connection URL to the DynamoDB instance
    Type: String
    Default: "http://dynamo-local:8000"
  RedisURL: #Connection URL to the Redis cache cluster instance
    Type: String
    Default: "redis://password@localhost:6379/"  
  CacheEnabled: #If enabled, cache is used
    Type: String
    Default: "false"
  CacheOnly: #If enabled, only cache is used without going to database (cache must be enabled)
    Type: String
    Default: "false"
  QueryFactory: #Factory class used to configure the querying to the data layer
    Type: String
    Default: "shorturls.dynamodao.config.DynamoDAOFactory"
  BaseURL: #Base URL of short URLs that are generated, e.g. http://me.li
    Type: String
    Default: "http://localhost:3000"
  EventsFactory: #Factory class used to configure events sending 
    Type: String
    Default:  "shorturls.events.dynamo.config.DynamoEventsFactory"
  CacheFactory: #Factory class used to configure cache
    Type: String
    Default: "shorturls.cache.config.RedisCacheFactory"   
  KafkaBrokers:  #List of comma separated connections to brokers
    Type: String
    Default: "kafka:29092"
  KafkaClientId:  #Client id used to communicate to Kafka
    Type: String
    Default: "client1"
  KafkaTopicName: #Kafka topic where the event is sent to 
    Type: String
    Default: "geturl"
  KafkaEnabled:  #If enabled, events are sent to the kafka instance configured
    Type: String
    Default: "false"
  RandomAlphabet: #Alphabet used for generating short URLs
    Type: String
    Default: "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
  DynamoRandomRange: #Random range used as suffix of partition keys for avoiding hot partitions on DynamoDB
    Type: Number
    Default: 5
    MinValue: 1
  CookieConfig: #Cookie configuration for the cookie sent to the request agent 
    Type: String
    Default: "; samesite=Strict"
Resources:
  RedirectShortURLFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ../redirectshorturl
      Handler: redirectshorturl.apigateway.RedirectShortURLGW::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      Policies:
      - AmazonDynamoDBFullAccess
      - AmazonVPCCrossAccountNetworkInterfaceOperations
      MemorySize: 512
      Environment: 
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 
          DYNAMO_URL: !Ref DynamoURL
          REDIS_URL: !Ref RedisURL
          CACHE_ENABLED: !Ref CacheEnabled
          QUERY_FACTORY: !Ref QueryFactory
          BASE_URL: !Ref BaseURL
          CACHE_FACTORY: !Ref CacheFactory
          EVENTS_FACTORY: !Ref EventsFactory
          KAFKA_BROKERS: !Ref KafkaBrokers
          KAFKA_CLIENTID: !Ref KafkaClientId
          KAFKA_TOPICNAME: !Ref KafkaTopicName
          KAFKA_ENABLED: !Ref KafkaEnabled
          RANDOM_ALPHABET: !Ref RandomAlphabet
          DYNAMO_RANDOM_RANGE: !Ref DynamoRandomRange
          COOKIE_CONFIG: !Ref CookieConfig
          CACHE_ONLY: !Ref CacheOnly
      Events:
        RedirectShortURLEvent:
          Type: Api 
          Properties:
            Path: /{code}
            Method: get